name: CMake CI workflow name

on:
  push:
  pull_request:

jobs:
  cmake_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vii/partvwap-docker:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure project
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: make -C build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure