name: CMake CI workflow name

on:
  push:
  pull_request:

jobs:
  cmake_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.3'

      - name: Configure project
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Debug -- -j$(nproc)

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure