name: CMake CI workflow name

on:
  push:
  pull_request:

jobs:
  cmake_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Boost and Thrift and CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev libthrift-dev cmake

      - name: Configure project
        run: cmake -S . -B build --config Release

      - name: Build
        continue-on-error: true
        run: make -C build -k

      - name: Configure project again now that Arrow and Parquet are installed
        run: cmake -S . -B build --config Release

      - name: Build
        run: make -C build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure