name: CMake UBSAN workflow name

on:
  push:
  pull_request:

jobs:
  cmake_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vii/partvwap-docker:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure project with clang and sanitizers
        run: CC=clang CXX=clang++ cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fsanitize=leak,undefined" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=leak,undefined"

      - name: Build
        run: make -C build -j4

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure